### ISSUE TITLE
Recently View Page - Improper Information

### ISSUE THREAD

**Issue by vishals79** [hanumakanthvvn/exercism.io#46]
![recently viewed](https://cloud.githubusercontent.com/assets/12394354/7880130/622a96b8-0614-11e5-8117-1ccac4c45991.png)

**Comment by praveenpuglia** [comment]
looks to me like angular loading failure. what are the steps to reproduce?

**Comment by vishals79** [comment]
Steps to reproduce:
1. After log-in, click on user name to open drop down.
2. Click on "Recently Viewed".
![recently viewed option](https://cloud.githubusercontent.com/assets/12394354/7880888/49acaf20-061b-11e5-9824-d5f5f0134d9d.png)

**Comment by praveenpuglia** [comment]
Fixed in latest builds by @hanumakanthvvn  - this commit e192cf89c237b6fe0cfc81127d3a644c912880c6
