### ISSUE TITLE
Page Crash on click of assignment hyperlink

### ISSUE THREAD

**Issue by vishals79** [hanumakanthvvn/exercism.io#47]
Steps to replicate:
1. Submitted an assignment
2. Delete the assignment
3. Link for assignment is still visible
4. Clicked on the hyperlink
5. Page Crash
![account page](https://cloud.githubusercontent.com/assets/12394354/7880175/d1c41a4e-0614-11e5-94e9-ad0f1c249a7b.png)
![page crash](https://cloud.githubusercontent.com/assets/12394354/7880176/d4d4cb20-0614-11e5-8f90-89f3f4855267.png)

**Comment by praveenpuglia** [comment]
Same here! This seems to be like a back-end data issue @hanumakanthvvn @SaiVardhan  ?

**Comment by SaiVardhan** [comment]
It seems to be working fine.Can you please recheck once at your side.

**Comment by praveenpuglia** [comment]
@SaiVardhan  - Nope! I still get that error. I think @vishals79  has deleted the project but it still is showing up which is why it throws a sorry page.

**Comment by SaiVardhan** [comment]
@vishals79 , @praveenpuglia  we have cleared your submissions stuff can you please try to reproduce it again..?

**Comment by praveenpuglia** [comment]
deleted project submissions should either not be listed or not be linked. this leads to sorry page.
