### ISSUE TITLE
Page crash on clicking project link

### ISSUE THREAD

**Issue by shrutig** [hanumakanthvvn/exercism.io#66]
![image](https://cloud.githubusercontent.com/assets/1889572/9322537/3ab51e56-4592-11e5-98b1-82df2e655e5b.png)
On clicking the Inventory Management link I got the following error. 
![image](https://cloud.githubusercontent.com/assets/1889572/9322547/602856bc-4592-11e5-946c-4498073bb3a9.png)

**Comment by SaiVardhan** [comment]
Can you rename the Github repository from InventoryManagement to inventory-management and try it once.

**Comment by hanumakanthvvn** [comment]
Can you rename the Github repository from InventoryManagement to inventory-management and try it once.

**Comment by shrutig** [comment]
Yes, it worked on renaming the Github repository. Thanks.
